// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * Supabase Client Configuration
 *
 * IMPORTANTE: Este cliente usa variáveis de ambiente para configuração.
 * As seguintes variáveis devem estar definidas no arquivo .env:
 *
 * - VITE_SUPABASE_URL: URL do projeto Supabase
 * - VITE_SUPABASE_ANON_KEY: Chave pública (anon/publishable) do Supabase
 *
 * ATENÇÃO: A variável VITE_SUPABASE_ANON_KEY deve conter APENAS o token JWT,
 * sem o prefixo "Bearer ". Exemplo correto:
 *   VITE_SUPABASE_ANON_KEY="eyJhbGc..."
 * Exemplo ERRADO:
 *   VITE_SUPABASE_ANON_KEY="Bearer eyJhbGc..."
 */

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Guard: valida que as variáveis de ambiente estão definidas
if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error(
    "Missing Supabase environment variables. " +
    "Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are defined in your .env file."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
