// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbyjnoymzdjtyzsgkeba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZieWpub3ltemRqdHl6c2drZWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzOTgzMzUsImV4cCI6MjA3ODk3NDMzNX0.QOTCJTaWDmQBYfQHWRnFDL2VC03crdq7KWC-jOtUJz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});